####################################################################
####   crdviya.yml                                                                   ####
####################################################################
####################################################################
#### Author: SAS Institute Inc.                                                                                       ####
####                                                                                                                                           ####
####################################################################
####################################################################
#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: viyas.company.com
spec: 
   group: company.com
   version: v1
   scope: Namespaced
   names: 
      plural: viyas
      kind: Viya
      shortNames:
      - vyc
