####################################################################
####   crservice_acct.yml                                                                   ####
####################################################################
####################################################################
#### Author: SAS Institute Inc.                                                                                       ####
####                                                                                                                                           ####
####################################################################
####################################################################
#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ServiceAccount
metadata:
    name: crreader


