####################################################################
####   viya-rolebinding.yml                                    ####
####################################################################
####################################################################
#### Author: SAS Institute Inc.                                                                                       ####
####                                                                                                                                           ####
####################################################################
####################################################################
#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viyasrolebinding
subjects:
- kind: ServiceAccount
  name: crreader
roleRef:
  kind: Role
  name: viyasrole
  apiGroup: rbac.authorization.k8s.io
